/**
 * Session-related constants and enums shared across services
 */

export enum SessionStatus {
  SCHEDULED = 'SCHEDULED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  NO_SHOW = 'NO_SHOW',
  RESCHEDULED = 'RESCHEDULED',
}

export enum SessionType {
  ONE_ON_ONE = 'ONE_ON_ONE',
  GROUP = 'GROUP',
  WORKSHOP = 'WORKSHOP',
  TRIAL = 'TRIAL',
}

export enum CancellationReason {
  STUDENT_REQUEST = 'STUDENT_REQUEST',
  TUTOR_REQUEST = 'TUTOR_REQUEST',
  EMERGENCY = 'EMERGENCY',
  TECHNICAL_ISSUES = 'TECHNICAL_ISSUES',
  NO_SHOW_STUDENT = 'NO_SHOW_STUDENT',
  NO_SHOW_TUTOR = 'NO_SHOW_TUTOR',
  SYSTEM_ERROR = 'SYSTEM_ERROR',
}

// Session timing constants
export const SESSION_TIMING = {
  MIN_DURATION_MINUTES: 30,
  MAX_DURATION_MINUTES: 180,
  DEFAULT_DURATION_MINUTES: 60,
  BUFFER_TIME_MINUTES: 15,
  CANCELLATION_DEADLINE_HOURS: 24,
  RESCHEDULE_DEADLINE_HOURS: 48,
} as const;

// Session validation constants
export const SESSION_VALIDATION = {
  MAX_NOTES_LENGTH: 2000,
  MAX_AGENDA_LENGTH: 1000,
  MAX_PARTICIPANTS_GROUP: 8,
  MIN_ADVANCE_BOOKING_HOURS: 2,
  MAX_ADVANCE_BOOKING_DAYS: 90,
} as const;